name: Publish demandresponse.schema.json
on:
  push:
    branches:
      - main
    paths:
      - '**/DemandResponse/v1/demandresponse.schema.json'
      
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Note: The $web container must be manually escaped as \$web in the SAS URL in the secret or this will fail!
    - name: Publish schema file
      run: |
        azcopy copy ./DemandResponse/v1/demandresponse.schema.json "${{ secrets.PUBLIC_SCHEMA_SAS_URL }}"
