name: Pack Wiki Files

on:
  gollum:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: hiloenergie/schema.wiki

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install -g jszip-cli

    - name: Get the date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      #run: echo "::set-output name=date::$(date +'%Y%m%d')"
    
    - name: Zip markdown files
      run: jszip -o hilo-connect-r${{ vars.HILO_CONNECT_VERSION }}-${{ steps.date.outputs.date }}.zip *.md *.png

    - name: Push zip to artifacts (90 day lifetime)
      uses: actions/upload-artifact@v4
      with:
        name: 'hilo-connect-r${{ vars.HILO_CONNECT_VERSION }}-${{ steps.date.outputs.date }}'
        path: hilo-connect-r${{ vars.HILO_CONNECT_VERSION }}-${{ steps.date.outputs.date }}.zip
        retention-days: 90

  
